### ISSUE TITLE
Put node shows error triangle for missing bucket

### ISSUE THREAD

**Issue by DrZeta360** [O-Hahn/node-red-contrib-cos#10]
If the bucket is missing in the configuration the node shows the error triangle (as shown in the image below). Nonetheless, if the bucket is provided in the message the node works fine.
Obviously it's not a big issue, but I thought you'd like to know.
Thanks!
![Capture2](https://user-images.githubusercontent.com/26259399/63431045-e82aff00-c415-11e9-8ce4-40be39cd29c2.PNG)

**Comment by O-Hahn** [comment]
you are right - bucket is a mandatory field - and could be overridden by the msg.bucket. Because of defining it mandatory in the config - the error is shown. The same behavior is in several other nodes - so if you always override it with your flow-parameters (like change) - write a default to avoid this notification.
